[book]
authors = ["The PHP Group"]
language = "en"
multilingual = false
src = "src"
title = "PHP Language Specification"

[build]
build-dir = "book"
create-missing = false

[output.html]
additional-css = ["src/css/style.css"]
curly-quotes = true
git-repository-url = "https://github.com/php/php-langspec"
