<?php

$welcomeFile = realpath(dirname(__FILE__) . '/../src/welcome.md');
$repoDir = realpath(dirname(__FILE__) . '/..');
$langspecDir = realpath(dirname(__FILE__) . '/../php-langspec');

chdir($repoDir);
$repoHash = exec('git rev-parse HEAD');
$repoShortHash = substr($repoHash, 0, 7);

chdir($langspecDir);
$langspecHash = exec('git rev-parse HEAD');
$langspecShortHash = substr($langspecHash, 0, 7);

$generationDate = gmdate('j F Y \a\t H:i e');

$colophonPattern = "/<!-- Begin Colophon -->(.*)<!-- End Colophon -->\n/s";

$colophon = <<<EOT
<!-- Begin Colophon -->
<!-- This is autogenerated. Do not remove the lines "Begin Colophon" or "End Colophon". -->
This documentation was generated on {$generationDate} from
[php/php-langspec@{$langspecShortHash}](https://github.com/php/php-langspec/tree/{$langspecHash})
and [phpcommunity/phplang.org@{$repoShortHash}](https://github.com/phpcommunity/phplang.org/tree/{$repoHash}).
<!-- End Colophon -->

EOT;

$welcome = file_get_contents($welcomeFile);
$welcome = preg_replace($colophonPattern, $colophon, $welcome);

file_put_contents($welcomeFile, $welcome);

echo "Colophon generated!\n";
